config/routes.rb
Rails.application.routes.draw do
  # resources :articles, only: [:show] # This will only enable the show route among all the others request
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get "about", to: "pages#about"
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  match '*unmatched', to: 'application#not_found_method', via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:6, maximum:100}
  validates :description, presence: true, length: {minimum:6, maximum:300}

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum:3, maximum:25}

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum:105}, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [ :show, :index]
  before_action :require_same_user, only: [ :edit, :update, :destory ]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        flash[:notice] = "Article was created."
        format.html { redirect_to article_path(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        # render :new, notice: "Some error occured."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      # debugger #It will pause the server and will show where you are in your code
      begin
        @article = Article.find(params[:id])
      rescue => exception
        redirect_to articles_path, notice: exception
      end
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user
        flash[:alert] = "You are only allowed to edit your own articles."
        redirect_to articles_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def login
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in Successfully"
      redirect_to user_path(user)
    else
      flash.now[:notice] = "There was something wrong with your login details"
      render :new, status: :unprocessable_entity
    end
  end

  def logout
    if(session[:user_id])
      session[:user_id] = nil
      flash[:notice] = "You have been logged out"
      redirect_to root_path
    else
      flash[:notice] = "You should first login"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [ :show, :index, :new]
  before_action :require_same_user, only: [ :edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice]="Welcome to Alpha Blog #{@user.username}, you have been succesfully signed up"
      redirect_to articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if User.update(user_params)
      redirect_to user_path(@user), notice: "Profile updated successfully"
    else
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:alert] = "Your account and all of your articles are deleted successfully."
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    begin
      @user = User.find(params[:id])
    rescue => exception
      redirect_to root_path , notice: exception
    end
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "You are only allowed to edit your own profile."
      redirect_to articles_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in."
      redirect_to login_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="article-container">
  <div class="row">
    <div class="col">
      <div class="card mt-4 shadow bg-body rounded">
        <div class="card-header text-center">
          By <%= article.user.username %>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= truncate(article.description, length: 50) %></p>
        </div>
        <div class="card-footer text-muted text-center">
          Created
          <%= time_ago_in_words(article.created_at) %>
          ago, updated
          <%= time_ago_in_words(article.updated_at) %>
          ago
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex mt-3 justify-content-center"">
    <%= link_to "Back to articles", articles_path, class: "btn btn-success" %>
  </div>
</div>

app/views/articles/_articles.html.erb
<div id="articles">
  <div class="row row-cols-2">
    <% obj.each do |article| %>
      <div class="col">
        <div class="card mt-4 shadow bg-body rounded">
          <div class="card-heading card-header text-center">
            <% if article.user %>
              By
              <%= link_to article.user.username, user_path(article.user), class: "link-success" %>
            <% else %>
              Anonymous
            <% end %>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><%= truncate(article.description, length: 50) %></p>
            <%= link_to "View Article", article_path(article), class: "btn btn-success" %>
            <% if logged_in? && current_user == article.user %>
              <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-success" %>
            <% end %>
          </div>
          <div class="card-footer text-muted text-center">
            Created
            <%= time_ago_in_words(article.created_at) %>
            ago, updated
            <%= time_ago_in_words(article.updated_at) %>
            ago
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if logged_in? && !obj.empty? %>
    <% if current_user == obj.first.user %>
      <%= link_to "Add a New article",
      new_article_path,
      class: "btn btn-success new-btn mt-4" %>
    <% elsif params.require(:controller) == "articles" %>
      <%= link_to "Add a New article",
      new_article_path,
      class: "btn btn-success new-btn mt-4" %>
    <% end %>
  <% end %>
</div>
<div class="apple_pagination mb-0">
  <%= will_paginate obj, container: false %>
</div>

app/views/articles/_form.html.erb
<div class="form-container position-relative">
  <%= form_with(model: article) do |form| %>
    <%= render "shared/errors", obj: @article %>

    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>

    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>

    <div class="d-inline-flex mt-3">
      <%= form.submit class: "btn btn-success" %>
      <%= link_to "Back to articles", articles_path, class: "btn btn-success mx-2" %>
    </div>
  <% end %>
  <% if params.require("action") == "edit" %>
    <div class="d-flex align-items-end justify-content-end position-absolute end-0 bottom-0">
    <%= button_to "Destroy this article",
    article_path(@article),
    class: "btn btn-danger",
    method: :delete,
    form: {
      data: {
        turbo_confirm: "Are you sure?"
      }
    } %>
  </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="page-heading">Editing article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center page-heading">List of all the Articles</h1>


<%= render "articles", obj: @articles %>

<div class="apple_pagination mb-0">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="page-heading">Add a new article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <% if logged_in?%>
      <%= link_to "Alpha Blog", articles_path , class:"navbar-brand" , id:"logo" %>
    <% else %>
      <%= link_to "Alpha Blog", root_path , class:"navbar-brand" , id:"logo" %>
    <% end %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-section navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Users", users_path , class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link active"%>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Log Out", logout_path , class: "nav-link active",method: :delete %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.username , user_path(current_user) , class: "nav-link active"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path , class: "nav-link active"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up" , signup_path , class: "nav-link active"%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-outline-success" type="submit">
          Search
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <%= stylesheet_link_tag "style.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
  </body>
  
  <div class="footer">
    <p>Copyright @ Harsh Yadav</p>
  </div>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to "Home page", root_path %> |
<%= link_to "Article Listing", articles_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron p-5 mb-4 bg-body-tertiary rounded-3 text-center">
    <div class="container-fluid py-5">
      <h1 id="home-container-heading" class="display-5 fw-bold">Alpha Blog</h1>
      <p class="col-md-8 fs-4" id="home-container-para">
        Using a series of utilities, you can create this jumbotron, just like
        the one in previous versions of Bootstrap. Check out the examples below
        for how you can remix and restyle it to your liking.
      </p>
      <%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="form-container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <%= pluralize(obj.errors.count, "error")%>
            prohibited this <%= obj.class.name.downcase %> from being saved:
        </h4>
        <ul>
            <% obj.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render "shared/errors", obj: @user %>
  <div class="form-container">

    <%= form.label :username, class: "form-label" %>
    <%= form.text_field :username, class: "form-control" %>

    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>

    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>

    <div class="d-flex mt-3">
      <% if params.require("action") == "new"%>
        <%= form.submit "Sign Up", class: "btn btn-success" %>
        <%= link_to "Back to Home", root_path, class: "btn btn-success mx-2" %>
      <% else%>
        <%= form.submit class: "btn btn-success" %>
        <%= link_to "Back to Profile", user_path(@user), class: "btn btn-success mx-2" %>
      <% end%>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="page-heading">Edit Your Profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="page-heading pt-2">Aplha Bloggers</h1>
<div class="d-flex justify-content-center align-items-center py-3">
  <% @users.each do |user| %>
    <div class="card text-center mx-2" style="width: 28rem;">
      <img
        src="https://media.istockphoto.com/id/1433039224/photo/blue-user-3d-icon-person-profile-concept-isolated-on-white-background-with-social-member.jpg?b=1&s=170667a&w=0&k=20&c=X-ZNF80_ASKvWpbOICHC8Pf27CFCRyh7Ce9SDVopjZg="
        class="card-img-top"
        height="400"
        width="300"
        alt="#"
      >
      <div class="card-body">
        <h5 class="card-title"><%= user.username %></h5>
        <p class="card-text"><%= pluralize(user.articles.count, "Article") %>
        </p>
        <%= link_to "View Articles", user_path(user) , class: "btn btn-success" %>
        <% if logged_in? && current_user == user %>
          <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="card-footer text-muted text-center">
        Joined
        <%= time_ago_in_words(user.created_at) %>
        ago
      </div>
    </div>
  <% end %>
  <div class="apple_pagination mb-0">
    <%= will_paginate @users, container: false %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="page-heading">Sign up for Alpha blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="page-heading pt-2"><%= @user.username %>
  Profile</h1>
<img
  src="https://media.istockphoto.com/id/1433039224/photo/blue-user-3d-icon-person-profile-concept-isolated-on-white-background-with-social-member.jpg?b=1&s=170667a&w=0&k=20&c=X-ZNF80_ASKvWpbOICHC8Pf27CFCRyh7Ce9SDVopjZg="
  class="rounded mx-auto d-block"
  height="200"
  width="200"
  alt="#"
>

<h3 class="text-center mt-4">
  <% if logged_in? && current_user == @user %>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-success" %>
    <%= button_to "Delete your profile",
    user_path,
    class: "profile-delete-btn btn btn-danger",
    method: :delete,
    form: {
      data: {
        turbo_confirm: "Are you sure?"
      }
    } %>
  <% end %>
</h3>

<h3 class="text-center mt-4">List of all the Articles</h3>

<%= render "articles/articles",
obj: @user.articles.paginate(page: params[:page], per_page: 2) %>